n=int(input('enter the value of n:'))
print('The value of n<<1=',n<<1)
print('The value of n<<2=',n<<2)
print('The value of n<<3=',n<<3)
print('The value of n<<4=',n<<4)
print('The value of n<<5=',n<<5)
print('The value of n<<6=',n<<6)
print('The value of n<<7=',n<<7)
print('The value of n<<8=',n<<8)
print('The value of n<<9=',n<<9)
print('The value of n<<10',n<<10)
