from tkinter import*
fb=Tk()
fb.title('student application form')
Label(fb,text='enter student id:').grid(row=0)
Label(fb,text='enter student name:').grid(row=1)
Label(fb,text='enter father name:').grid(row=2)
Label(fb,text='enter group:').grid(row=3)
Label(fb,text='enter phone number:').grid(row=4)
Label(fb,text='enter email:').grid(row=5)
Label(fb,text='enter address:').grid(row=6)
e1=Entry(fb)
e2=Entry(fb)
e3=Entry(fb)
e4=Entry(fb)
e5=Entry(fb)
e6=Entry(fb)
e7=Entry(fb)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e3.grid(row=2,column=1)
e4.grid(row=3,column=1)
e5.grid(row=4,column=1)
e6.grid(row=5,column=1)
e7.grid(row=6,column=1)
Button(fb,text='Login').grid(row=7)
Button(fb,text='Cancel').grid(row=7,column=1)
mainloop()
